Add validation to retrieve sku from marketplace
vtex-apps/availability-notify pull request #46
Opened 2022-03-09 06:01 UTC by albertm805

## Description
- Currently the seller sends the notification to the markeplace, and should notify. 
- The Sku mismatch doesn't allow this app to work unless the sku affiliation is correct

2022-03-09 12:02 UTC, btalma approved these changes

2022-03-11 20:50 UTC, polishq requested changes

2022-03-11 20:50 UTC, polishq commented on dotnet/Services/VtexAPIService.cs
> +                    Console.WriteLine(JsonConvert.SerializeObject(cartSimulationRequest));
Remove this line, otherwise LGTM

2022-03-11 20:59 UTC, polishq approved these changes

2022-03-11 21:06 UTC, merged